### ISSUE TITLE
Definition for rule 'jest/no-standalone-expect' was not found

### ISSUE THREAD

**Issue by creage** [playwright-community/eslint-plugin-jest-playwright#5]
Version 0.3.0 started to crash our build verifications with the error `Definition for rule 'jest/no-standalone-expect' was not found`;

Apparently, this rule is a part of [`eslint-plugin-jest`](https://github.com/jest-community/eslint-plugin-jest/blob/main/docs/rules/no-standalone-expect.md), which should be inherited/included?

**Comment by mxschmitt** [comment]
Should be fixed with 0.3.1. Thanks for reporting! :)
