### ISSUE TITLE
With >= 0.3.0 "Definition for rule 'jest-playwright/missing-playwright-await' was not found"

### ISSUE THREAD

**Issue by tkrotoff** [playwright-community/eslint-plugin-jest-playwright#8]
Since 0.3.0 (also with 0.3.1 and 0.3.2) it throws error "Definition for rule 'jest-playwright/missing-playwright-await' was not found"

No problem with 0.2.1.

**Comment by mxschmitt** [comment]
cc @mskelton would be awesome if you could take a look, many thanks!

**Comment by mskelton** [comment]
@tkrotoff With version 0.3.0, you will need to add `"plugins": ["jest-playwright"]` to your ESLint config.  So for example.

```diff
{
  "extends": ["plugin:jest-playwright/recommended"],
+ "plugins": ["jest-playwright"]
}
```
